name=input()
name=name.strip()
name=name.capitalize()
print(f"hello {name}, happy to see you here ")
age=int(input())
if age <16:
    print("error")
else:
    print("your welcome")
print("="*20)
f_name=input()
sec_name=input()
f_name=f_name.strip()
f_name=f_name.capitalize()
sec_name=sec_name.strip()
sec_name=sec_name.capitalize()
print(f"hello {f_name} {sec_name[0]}")
email=input()
email=email.strip()
email=email.lower()
print(email[0:email.index("@")].capitalize())
print(email[((email.index("@"))+1):email.index(".")])
print(email[((email.index("."))+1):])